source 'https://cdn.cocoapods.org/'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
platform :ios, '11.0'

# workaround for https://github.com/CocoaPods/CocoaPods/issues/8073
# need for correct invalidate of cache MultiPlatformLibrary.framework
install! 'cocoapods', :disable_input_output_paths => true

target 'TestProj' do
  pod 'MultiPlatformLibrary', :path => '../mpp-library'
  pod 'Firebase', '6.33.0'
  pod 'FirebaseCrashlytics', '4.6.1'
  
  # Firebase libraries already linked in moko-crash-reporting. Remove duplicated linking.
  post_install do |installer|
    host_targets = installer.aggregate_targets.select { |aggregate_target|
      aggregate_target.name.include? "Pods-"
    }
    
    host_targets.each do |host_target|
      host_target.xcconfigs.each do |config_name, config_file|
        config_file.frameworks.delete("FirebaseCore")
        config_file.frameworks.delete("FirebaseCrashlytics")
        config_file.frameworks.delete("FirebaseInstallations")
        config_file.frameworks.delete("GoogleDataTransport")
        
        xcconfig_path = host_target.xcconfig_path(config_name)
        config_file.save_as(xcconfig_path)
      end
    end
  end
end
